# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joseph's 20% Time Blog
email: camacjos0@bloomingtonacademy.org
description: > # this means to ignore newlines until "baseurl:"
  My adventures as I progress through my 20% time project.
  Special thanks to <a href="https://github.com/10by10pixel">Owen Walters</a> for tech help!
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  NarumiKazuko

# Build settings
markdown: kramdown
